kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: finlex-lukija
  labels:
    app: finlex-lukija
spec:
  lookupPolicy:
    local: false
  tags:
    - name: production
      from:
        kind: DockerImage
        name: toska/finlex:production
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local