apiVersion: v1
kind: ConfigMap
metadata:
  name: finlex-lukija-config
data:
  PG_URI: SECRET_PG_URI
  TYPESENSE_API_KEY: SECRET_TYPESENSE_API_KEY  ADMIN_PASSWORD: SECRET_ADMIN_PASSWORD
  JWT_SECRET: SECRET_JWT_SECRET
